#!/bin/bash
cd ./
node ./cleancart_activity.js
node ./jd_Elecsport.js
node ./jd_Last_Week_income.js
node ./jd_all_bean_change.js
node ./jd_angryKoi.js
node ./jd_api_test.js
node ./jd_babel_sign.js
node ./jd_bean_box.js
node ./jd_bean_change.js
node ./jd_bean_home.js
node ./jd_bean_sign.js
node ./jd_beauty.js
node ./jd_big_winner.js
node ./jd_bookshop.js
node ./jd_car.js
node ./jd_car_exchange.js
node ./jd_cash.js
node ./jd_ccSign.js
node ./jd_cfd.js
node ./jd_cfd_game.js
node ./jd_cfd_help.js
node ./jd_cfd_shell.js
node ./jd_cfd_stock.js
node ./jd_city.js
node ./jd_cjhz.js
node ./jd_club_lottery.js
node ./jd_connoisseur.js
node ./jd_daily_lottery.js
node ./jd_ddnc_farmpark.js
node ./jd_ddworld_exchange.js
node ./jd_dj_bean.js
node ./jd_dj_fruit.js
node ./jd_dj_fruit_collectWater.js
node ./jd_dj_getPoints.js
node ./jd_dj_plantBeans.js
node ./jd_dns_shop.js
node ./jd_dreamFactory.js
node ./jd_dreamFactory_help.js
node ./jd_dreamFactory_tuan.js
node ./jd_dwapp.js
node ./jd_exchange_joy.js
node ./jd_exchangejxbeans.js
node ./jd_family.js
node ./jd_foodRunning.js
node ./jd_fruit.js
node ./jd_fruit_moreTask.js
node ./jd_getUp.js
node ./jd_get_share_code.js
node ./jd_gold_creator.js
node ./jd_guaMMdou.js
node ./jd_guaUnknownTask7.js
node ./jd_guaUnknownTask9.js
node ./jd_guacleancart.js
node ./jd_guaopencard101.js
node ./jd_guaopencard109.js
node ./jd_guaopencard110.js
node ./jd_guaopencard111.js
node ./jd_guaopencard112.js
node ./jd_guaopencard93.js
node ./jd_guaopencard95.js
node ./jd_guaopencard96.js
node ./jd_guaopencard97.js
node ./jd_guaopencard98.js
node ./jd_guawealth_island.js
node ./jd_hcb_red.js
node ./jd_health.js
node ./jd_health2.js
node ./jd_health_collect.js
node ./jd_ifanli.js
node ./jd_jdfactory.js
node ./jd_jdtj_winner.js
node ./jd_jdzz.js
node ./jd_jin_tie.js
node ./jd_joy.js
node ./jd_joy_feedPets.js
node ./jd_joy_park.js
node ./jd_joy_park_task.js
node ./jd_joy_reward.js
node ./jd_joy_run.js
node ./jd_joy_steal.js
node ./jd_jump.js
node ./jd_jxbox.js
node ./jd_jxgc_stock.js
node ./jd_jxlhb.js
node ./jd_jxmc.js
node ./jd_jxnc.js
node ./jd_jxnnfls.js
node ./jd_jxqd.js
node ./jd_kd.js
node ./jd_live.js
node ./jd_live_redrain.js
node ./jd_lotteryMachine.js
node ./jd_lsj.js
node ./jd_m_sign.js
node ./jd_market_lottery.js
node ./jd_mhyyl.js
node ./jd_mhyyl_prize.js
node ./jd_mhyyl_sendCard.js
node ./jd_mohe.js
node ./jd_moneyTree.js
node ./jd_monopoly.js
node ./jd_mpdzcar.js
node ./jd_mpdzcar_game.js
node ./jd_mpdzcar_help.js
node ./jd_ms.js
node ./jd_necklace.js
node ./jd_newCron.js
node ./jd_nhRedEnvelope.js
node ./jd_nh_sign.js
node ./jd_nhs_red.js
node ./jd_nzmh.js
node ./jd_pet.js
node ./jd_pigPet.js
node ./jd_plantBean.js
node ./jd_price.js
node ./jd_productZ4Brand.js
node ./jd_qq_pasture.js
node ./jd_rankingList.js
node ./jd_redPacket.js
node ./jd_sendBeans.js
node ./jd_sgmh.js
node ./jd_shop.js
node ./jd_shop_sign.js
node ./jd_sign_graphics.js
node ./jd_sjnhj.js
node ./jd_sjzjd.js
node ./jd_speed.js
node ./jd_speed_redpocke.js
node ./jd_speed_sign.js
node ./jd_split.js
node ./jd_superBrand.js
node ./jd_superMarket.js
node ./jd_syj.js
node ./jd_track.js
node ./jd_try.js
node ./jd_ttpt.js
node ./jd_unsubscriLive.js
node ./jd_unsubscribe.js
node ./jd_validate_Worker.js
node ./jd_wish.js
node ./jd_work_validate.js
node ./jd_wxFans.js
node ./jd_wxFansli.js
node ./jd_wxFanspai_sign.js
node ./jd_xiaolong.js
node ./jd_xmf.js
node ./jd_yili_cow.js
node ./jd_zqfl.js
node ./sign_graphics_validate.js
